### ISSUE TITLE
Would you please release BERT-post and ELECTRA-post models? 

### ISSUE THREAD

**Issue by YawYoung** [taesunwhang/UMS-ResSel#2]
Would you please release BERT-post and ELECTRA-post models?

**Comment by taesunwhang** [comment]
Hi, you can download all post-trained checkpoints for three datasets (Ubuntu, Douban, and E-Commerce) that we used in our experiments by running `sh scripts/download_pretrained_checkpoints.sh`.

**Comment by YawYoung** [comment]
Thx ~!! ^-^
