### ISSUE TITLE
Hardware of training BERT post model

### ISSUE THREAD

**Issue by gmftbyGMFTBY** [taesunwhang/UMS-ResSel#4]
Hi, after reading your codes of post train, I realize that you leverage the `huggingface` BertForPreTraning module.
I reconstruct the post train codes, but I find it cost me about 12 hours to train one epoch.
My devices are 8 1080 Ti GPUs.

I want to know the hardware configuration during your experiments, and how much time cost for training one epoch in your settings.

**Comment by JudeLee19** [comment]
Hello, I'm the co-author of this paper. We conducted our experiments on the Kakao Brain Cloud with 4 Tesla V100 GPUs and took approximately 3 hours on 384 bach-size.

**Comment by gmftbyGMFTBY** [comment]
Thank you!
