### ISSUE TITLE
The difference in evaluation utils between the previous works and yours

### ISSUE THREAD

**Issue by gmftbyGMFTBY** [taesunwhang/UMS-ResSel#5]
Hello, thanks for your wonderful work.

Except for your codes, I also read other released response selection repos, and I found the difference in evaluation utils (only for douban corpus).

In [SA-BERT](https://github.com/JasonForJoy/SA-BERT/blob/4434ffb31fff33533076cb31eea8b450409b632d/metrics.py#L131), it can be found that, during calculating the R10@x scores, the previous work count when one positive sample are retrieved. But in your [codes](https://github.com/taesunwhang/UMS-ResSel/blob/825214d0a83bb0f936ae089639454e7eaeeeddbf/models/utils/scorer.py#L55), you calculate the average.
I am not sure which one is more appropriate, can you explain it to me?

Thank you very much!

**Comment by taesunwhang** [comment]
Hello again :) Sorry for late reply.

As Douban Corpus may contain more than one positive response (average 1.66 positive responses), Recall@k should be divided by the number of positive answers. 
For example, suppose that the number of candidates is 10 and the ground truths are positioned in 1st,  3rd, 5th, Recall@k(k=1,2,5) would be 0.33, 0.33, 1 (Recall@k should be divided into the number of ground truth answer). 
| Relevant  | O   | X   | O   | X   | O   | X   | X   | X   | X   | X    |
|-----------|-----|-----|-----|-----|-----|-----|-----|-----|-----|------|
| Precision | 1   | 1/2 | 2/3 | 2/4 | 3/5 | 3/6 | 3/7 | 3/8 | 3/9 | 3/10 |
| Recall    | 1/3 | 1/3 | 2/3 | 2/3 | 1   | 1   | 1   | 1   | 1   | 1    |

If there is only one positive response, recall@k would be either 1 or 0.
I believe [SA-BERT](https://arxiv.org/pdf/2004.03588.pdf) calculated the recall in the same way for Douban Corpus (The other two datasets (i.e., Ubuntu, E-Commerce) contain only one positive response in the test set). 

If you have more questions about the paper or code, feel free to ask!

**Comment by taesunwhang** [comment]
I think the [repo](https://github.com/JasonForJoy/SA-BERT/) by SA-BERT is dealing with Ubuntu Corpus only. 
[top_k_precision](https://github.com/JasonForJoy/SA-BERT/blob/4434ffb31fff33533076cb31eea8b450409b632d/metrics.py#L131) is the method of calculating Recall@k (k=1,2,5) when one positive response is in the candidates.

**Comment by gmftbyGMFTBY** [comment]
Thank you very much!
