### ISSUE TITLE
How do you choose checkpoint during training?

### ISSUE THREAD

**Issue by FFYYang** [taesunwhang/UMS-ResSel#6]
Hi, thanks for open source this wonderful work! I have a question about how to choose the checkpoint during training, since I notice that in the config file, the parameter `evaluate_data_type` is set to `test`.

```
ECOMMERCE_PARAMS = defaultdict(
  evaluate_candidates_num=10,
  recall_k_list=[1, 2, 5, 10],
  evaluate_data_type="test",
  language="chinese",
  max_utt_len=5,
)
```

**Comment by taesunwhang** [comment]
Hi, thanks for your interest in our work!
We choose the checkpoint which showed the best performance in R@1 in the development set (during the training period).  
When you evaluate the model for each epoch during training,  `evaluate_data_type` should be "dev".
If you have any questions, feel free to ask :)

**Comment by FFYYang** [comment]
Thanks!

**Comment by FFYYang** [comment]
Sorry, there is still a question, when I set `evaluate_data_type` to `dev`, should I also set `evaluate_candidates_num ` to 2?

**Comment by taesunwhang** [comment]
No problem. If you train the model on E-Commerce dataset, yes. set `evaluate_candidates_num` to 2  and `recall_k_list` to [1,2].

**Comment by FFYYang** [comment]
Thanks, it's clear now. But I find that the training is very slow. I try to use this script to train `UMS-BERT+` on four V100s (batch size=32), it takes about 20 hours for one epoch ....... 
```
python3 main.py --model bert_post --task_name ubuntu --data_dir data/ubuntu_corpus_v1 --bert_pretrained bert-post-uncased --bert_checkpoint_path bert-post-uncased-pytorch_model.pth --task_type response_selection --gpu_ids "0" --root_dir /path/to/root_dir --evaluate /path/to/checkpoints --multi_task_type "ins,del,srch"
```
