### ISSUE TITLE
Maybe a bug in dataset.py?

### ISSUE THREAD

**Issue by FFYYang** [taesunwhang/UMS-ResSel#7]
Thanks for open source your great work! I don't really understand what does this line used for.
https://github.com/taesunwhang/UMS-ResSel/blob/master/data/dataset.py#L93

**Comment by taesunwhang** [comment]
Hi, UMS are based on the dialog context. In that line, if the response is the ground truth (positive response), we include the response in the dialog context as the last utterance to apply UMS (not for the response selection task). This helps the case that the given dialog context is too short (not many turns).

**Comment by FFYYang** [comment]
Thanks! got it!
